### ISSUE TITLE
Nefarius.Utilities.Bluetooth.Exceptions.HostRadioException: Bluetooth host radio not found.

### ISSUE THREAD

**Issue by nefarius** [nefarius/BthPS3#112]
Reported by `kieran1847` on Discord:

```
Calling custom action BthPS3Installer!Nefarius.BthPS3.Setup.CustomActions.InstallDrivers
Removing lower filter entry
Removed lower filter entry
Disabling BthPS3 service
Disabled BthPS3 service
Disabling radio
Disabled radio
Restarting radio device
Restarted radio device
Exception thrown by custom action:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Nefarius.Utilities.Bluetooth.Exceptions.HostRadioException: Bluetooth host radio not found.
   at Nefarius.Utilities.Bluetooth.HostRadio..ctor(Boolean autoEnable)
   at Nefarius.BthPS3.Setup.CustomActions.UninstallDrivers(Session session)
   at Nefarius.BthPS3.Setup.CustomActions.InstallDrivers(Session session)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at WixToolset.Dtf.WindowsInstaller.CustomActionProxy.InvokeCustomAction(Int32 sessionHandle, String entryPoint, IntPtr remotingDelegatePtr)
CustomAction InstallDrivers returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 20:21:12: InstallFinalize. Return value 3.
```

**Comment by nefarius** [comment]
Fixed in v2.10.1
